name: Deploy to server on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: pull latest code on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/docker/biblioteka
            git config --global --add safe.directory /srv/docker/biblioteka
            git pull origin main
            echo "[DEPLOY] Restarting Docker containers"
            docker-compose down
            docker-compose up -d
